// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"qianshi/service/vcode/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/email",
				Handler: sendEmailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/vcode"),
	)
}
