// Code generated by goctl. DO NOT EDIT.
// Source: authentication.proto

package authentication

import (
	"context"

	"qianshi/app/authentication/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GenerateRefreshTokenReq  = __.GenerateRefreshTokenReq
	GenerateRefreshTokenResp = __.GenerateRefreshTokenResp
	GenerateTokenReq         = __.GenerateTokenReq
	GenerateTokenResp        = __.GenerateTokenResp
	VerifyRefreshTokenReq    = __.VerifyRefreshTokenReq
	VerifyRefreshTokenResp   = __.VerifyRefreshTokenResp
	VerifyTokenReq           = __.VerifyTokenReq
	VerifyTokenResp          = __.VerifyTokenResp

	Authentication interface {
		GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error)
		GenerateRefreshToken(ctx context.Context, in *GenerateRefreshTokenReq, opts ...grpc.CallOption) (*GenerateRefreshTokenResp, error)
		VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error)
		VerifyRefreshToken(ctx context.Context, in *VerifyRefreshTokenReq, opts ...grpc.CallOption) (*VerifyRefreshTokenResp, error)
	}

	defaultAuthentication struct {
		cli zrpc.Client
	}
)

func NewAuthentication(cli zrpc.Client) Authentication {
	return &defaultAuthentication{
		cli: cli,
	}
}

func (m *defaultAuthentication) GenerateToken(ctx context.Context, in *GenerateTokenReq, opts ...grpc.CallOption) (*GenerateTokenResp, error) {
	client := __.NewAuthenticationClient(m.cli.Conn())
	return client.GenerateToken(ctx, in, opts...)
}

func (m *defaultAuthentication) GenerateRefreshToken(ctx context.Context, in *GenerateRefreshTokenReq, opts ...grpc.CallOption) (*GenerateRefreshTokenResp, error) {
	client := __.NewAuthenticationClient(m.cli.Conn())
	return client.GenerateRefreshToken(ctx, in, opts...)
}

func (m *defaultAuthentication) VerifyToken(ctx context.Context, in *VerifyTokenReq, opts ...grpc.CallOption) (*VerifyTokenResp, error) {
	client := __.NewAuthenticationClient(m.cli.Conn())
	return client.VerifyToken(ctx, in, opts...)
}

func (m *defaultAuthentication) VerifyRefreshToken(ctx context.Context, in *VerifyRefreshTokenReq, opts ...grpc.CallOption) (*VerifyRefreshTokenResp, error) {
	client := __.NewAuthenticationClient(m.cli.Conn())
	return client.VerifyRefreshToken(ctx, in, opts...)
}
