// Code generated by goctl. DO NOT EDIT.
package types

type GetCaptchaIdResp struct {
	Id  string `json:"id"`
	Src string `json:"src"`
}

type GetCaptchaPngReq struct {
	Id string `path:"id"`
}

type RefreshCaptchaReq struct {
	Id string `path:"id"`
}

type VerifyCaptchaReq struct {
	Id     string `json:"id"`
	Digits string `json:"digits"`
}
