// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email     string `json:"email"`
	CaptchaId string `json:"captcha_id"`
}

type ChangePasswordReq struct {
	CaptchaId string `json:"captcha_id"`
}

type ChangeEmailReq struct {
	Email     string `json:"email"`
	CaptchaId string `json:"captcha_id"`
}

type EmailResp struct {
	Ttl int `json:"ttl"`
}
