// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email     string `json:"email"`
	CaptchaId string `json:"captcha_id"`
}

type LoginResp struct {
	Ttl int `json:"ttl"`
}
