// Code generated by goctl. DO NOT EDIT.
package types

type EmailReq struct {
	Email     string `json:"email"`
	CaptchaId string `json:"captcha_id"`
}

type EmailResp struct {
	Ttl int `json:"ttl"`
}
