// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "qianshi/app/user/cmd/api/internal/handler/login"
	me "qianshi/app/user/cmd/api/internal/handler/me"
	user "qianshi/app/user/cmd/api/internal/handler/user"
	"qianshi/app/user/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/email",
				Handler: login.EmailLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pass",
				Handler: login.PassLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user/login"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/exp",
				Handler: me.MeExpHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: me.MeInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/info",
				Handler: me.MeInfoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/security",
				Handler: me.MeSecurityHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/coin",
				Handler: me.MeCoinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pass/verify",
				Handler: me.MePassVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/pass/change",
				Handler: me.MePassChangeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/avatar",
				Handler: me.MeAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/power",
				Handler: me.MePowerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/email/verify",
				Handler: me.MeEmailVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/email/change",
				Handler: me.MeEmailChangeHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/signature",
				Handler: me.MeSigUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/top-img-no",
				Handler: me.MeTopImgNoUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user/me"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: user.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user"),
	)
}
