// Code generated by goctl. DO NOT EDIT.
package types

type GenerateResp struct {
	Id string `json:"id"`
}

type GetReq struct {
	Id string `path:"id"`
}

type GetResp struct {
	Image string `json:"image"`
}

type ReloadReq struct {
	Id string `json:"id"`
}

type VerifyReq struct {
	Id   string `json:"id"`
	Code string `json:"code"`
}
