// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	image "qianshi/app/captcha/cmd/api/internal/handler/image"
	"qianshi/app/captcha/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: image.GenerateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: image.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reload",
				Handler: image.ReloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: image.VerifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/captcha/image"),
	)
}
