// Code generated by goctl. DO NOT EDIT.
package types

type SendEmailReq struct {
	Email string `json:"email"`
	Cid   string `json:"cid"`
}

type SendEmailResp struct {
	CD int `json:"cd,omitempty"`
}
