// Code generated by goctl. DO NOT EDIT.
package types

type EmailLoginReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type PassLoginReq struct {
	Email string `json:"email"`
	Pass  string `json:"pass"`
}

type LoginResp struct {
	Token         string `json:"token"`
	RefreshToken  string `json:"refreshToken"`
	Nickname      string `json:"nickname"`
	AvatarUrl     string `json:"avatarUrl"`
	NewMessageNum int    `json:"newMessageNum"`
	NewDynamicNum int    `json:"newDynamicNum"`
}

type MeExpResp struct {
	Nickname string `json:"nickname"`
	Exp      int    `json:"exp"`
	Level    int    `json:"level"`
}

type MeInfoResp struct {
	Nickname  string   `json:"nickname"`
	Signature string   `json:"signature"`
	Gender    string   `json:"gender"`
	Birthday  string   `json:"birthday"`
	Tags      []string `json:"tags"`
}

type MeInfoUpdateReq struct {
	Nickname  string   `json:"nickname"`
	Signature string   `json:"signature"`
	Gender    string   `json:"gender"`
	Birthday  string   `json:"birthday"`
	Tags      []string `json:"tags"`
}

type MeSecurityResp struct {
	IsSetPassword bool   `json:"isSetPassword"`
	Email         string `json:"email"`
}

type MeCoinResp struct {
	Coin int `json:"coin"`
}

type MePassVerifyReq struct {
	Code string `json:"code"`
}

type MePassVerifyResp struct {
	Ttl int `json:"ttl"`
}

type MePassChangeReq struct {
	Pass string `json:"pass"`
}

type MePassChangeResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}

type MeAvatarResp struct {
	AvatarUrl string `json:"avatarUrl"`
}

type MePowerResp struct {
	Power int `json:"power"`
}

type MeEmailVerifyReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type MeEmailVerifyResp struct {
	Ttl int `json:"ttl"`
}

type MeEmailChangeReq struct {
	Email string `json:"email"`
}

type MeSigUpdateReq struct {
	NewSignature string `json:"newSignature"`
}

type MeTopImgNoUpdateReq struct {
	TopImgNo int `json:"topImgNo"`
}

type UserInfoReq struct {
	Id uint64 `path:"id"`
}

type UserInfoResp struct {
	Uid           int    `json:"uid"`
	Nickname      string `json:"nickname"`
	Signature     string `json:"signature"`
	AvatarUrl     string `json:"avatarUrl"`
	Gender        string `json:"gender"`
	Level         int    `json:"level"`
	IsVip         bool   `json:"isVip"`
	IpLocation    string `json:"ipLocation"`
	TopImgNo      int    `json:"topImgNo"`
	IsFocu        bool   `json:"isFocu"`
	IsBlock       bool   `json:"isBlock"`
	PostNum       int    `json:"postNum"`
	CollectionNum int    `json:"collectionNum"`
	FavlistNum    int    `json:"favlistNum"`
	FollowNum     int    `json:"followNum"`
	FanNum        int    `json:"fanNum"`
	LikeNum       int    `json:"likeNum"`
	PlayNum       int    `json:"playNum"`
	ReadNum       int    `json:"readNum"`
}
