// Code generated by goctl. DO NOT EDIT.
package types

type EmailLoginReq struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

type PassLoginReq struct {
	Email string `json:"email"`
	Pass  string `json:"pass"`
}

type LoginResp struct {
	Token         string `json:"token"`
	RefreshToken  string `json:"refreshToken"`
	Nickname      string `json:"nickname"`
	AvatarUrl     string `json:"avatarUrl"`
	NewMessageNum int    `json:"newMessageNum"`
	NewDynamicNum int    `json:"newDynamicNum"`
}

type MeExpResp struct {
	Nickname string `json:"nickname"`
	Exp      int    `json:"exp"`
	Level    int    `json:"level"`
}

type MeInfoResp struct {
	Nickname  string   `json:"nickname"`
	Signature string   `json:"signature"`
	Gender    string   `json:"gender"`
	Birthday  string   `json:"birthday"`
	Tags      []string `json:"tags,omitempty"`
}

type MeSecurityResp struct {
	IsSetPassword bool   `json:"isSetPassword"`
	Email         string `json:"email"`
}

type MeCoinResp struct {
	Coin int `json:"coin"`
}

type MePassVerifyReq struct {
	Code string `json:"code"`
}

type MePassChangeReq struct {
	Pass string `json:"pass"`
}

type MePassChangeResp struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refreshToken"`
}
