// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"qianshi/service/captcha/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: getCaptchaIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/captcha/:id",
				Handler: getCaptchaPngHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/captcha/:id",
				Handler: refreshCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/captcha/verify",
				Handler: verifyCaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
