// Code generated by goctl. DO NOT EDIT.
// Source: authentication.proto

package server

import (
	"context"

	"qianshi/app/authentication/cmd/rpc/internal/logic"
	"qianshi/app/authentication/cmd/rpc/internal/svc"
	"qianshi/app/authentication/cmd/rpc/pb"
)

type AuthenticationServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAuthenticationServer
}

func NewAuthenticationServer(svcCtx *svc.ServiceContext) *AuthenticationServer {
	return &AuthenticationServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthenticationServer) GenerateToken(ctx context.Context, in *__.GenerateTokenReq) (*__.GenerateTokenResp, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *AuthenticationServer) GenerateRefreshToken(ctx context.Context, in *__.GenerateRefreshTokenReq) (*__.GenerateRefreshTokenResp, error) {
	l := logic.NewGenerateRefreshTokenLogic(ctx, s.svcCtx)
	return l.GenerateRefreshToken(in)
}

func (s *AuthenticationServer) VerifyToken(ctx context.Context, in *__.VerifyTokenReq) (*__.VerifyTokenResp, error) {
	l := logic.NewVerifyTokenLogic(ctx, s.svcCtx)
	return l.VerifyToken(in)
}

func (s *AuthenticationServer) VerifyRefreshToken(ctx context.Context, in *__.VerifyRefreshTokenReq) (*__.VerifyRefreshTokenResp, error) {
	l := logic.NewVerifyRefreshTokenLogic(ctx, s.svcCtx)
	return l.VerifyRefreshToken(in)
}

func (s *AuthenticationServer) SignatureCdnGet(ctx context.Context, in *__.SignatureCdnGetReq) (*__.SignatureCdnGetResp, error) {
	l := logic.NewSignatureCdnGetLogic(ctx, s.svcCtx)
	return l.SignatureCdnGet(in)
}
